"""CpuAffinityTask — isolate management plane on CPU 2.

BCM Tomahawk IRQ storms saturate whichever CPUs receive the interrupts.
Pinning eth0 IRQs + TCP/IP softirq work (RPS/XPS) to CPU 2, steering BCM
IRQs away from CPU 2, and locking sshd/networking to CPU 2 keeps SSH and
DHCP responsive during storms regardless of ASIC interrupt rate.

Changes applied
---------------
1. /usr/local/bin/wedge100s-mgmt-affinity.sh
   Boot script: eth0 IRQ/RPS/XPS → CPU 2, BCM IRQs → CPUs 0,1,3-7.

2. /etc/systemd/system/wedge100s-mgmt-affinity.service
   Runs the script after networking.service on every boot.

3. /etc/systemd/system/ssh.service.d/cpu-affinity.conf
   CPUAffinity=2 — sshd and all per-connection children on CPU 2.

4. /etc/systemd/system/networking.service.d/cpu-affinity.conf
   CPUAffinity=2 — ifupdown2, dhclient children inherit CPU 2.
"""
import textwrap
from .base import Change, ConfigTask

MGMT_CPU = 2

AFFINITY_SCRIPT_PATH = "/usr/local/bin/wedge100s-mgmt-affinity.sh"
AFFINITY_SCRIPT = textwrap.dedent(f"""\
    #!/bin/bash
    # Isolate management plane on CPU {MGMT_CPU}.
    # Generated by CpuAffinityTask — do not edit by hand.
    set -euo pipefail

    MGMT_CPU={MGMT_CPU}
    MGMT_MASK=$(printf '%x' $((1 << MGMT_CPU)))
    NCPUS=$(nproc)
    ALL_MASK=$(( (1 << NCPUS) - 1 ))
    OTHER_MASK=$(printf '%x' $(( ALL_MASK & ~(1 << MGMT_CPU) )))

    # --- eth0: pin IRQs, RPS, XPS to CPU {MGMT_CPU} ---
    for irq in $(grep -w eth0 /proc/interrupts 2>/dev/null | awk -F: '{{print $1}}' | tr -d ' '); do
        echo "$MGMT_MASK" > /proc/irq/$irq/smp_affinity 2>/dev/null || true
    done
    for rps in /sys/class/net/eth0/queues/rx-*/rps_cpus; do
        echo "$MGMT_MASK" > "$rps" 2>/dev/null || true
    done
    for xps in /sys/class/net/eth0/queues/tx-*/xps_cpus; do
        echo "$MGMT_MASK" > "$xps" 2>/dev/null || true
    done

    # --- BCM/knet IRQs: steer away from CPU {MGMT_CPU} ---
    for irq in $(grep -iE 'bcm|knet|linux.bde|linux.uk.proxy' /proc/interrupts 2>/dev/null | awk -F: '{{print $1}}' | tr -d ' '); do
        echo "$OTHER_MASK" > /proc/irq/$irq/smp_affinity 2>/dev/null || true
    done

    echo "wedge100s-mgmt-affinity: management plane pinned to CPU $MGMT_CPU"
""")

AFFINITY_SERVICE_PATH = "/etc/systemd/system/wedge100s-mgmt-affinity.service"
AFFINITY_SERVICE = textwrap.dedent("""\
    [Unit]
    Description=Pin Wedge100S management plane to CPU 2
    After=networking.service
    Wants=networking.service

    [Service]
    Type=oneshot
    ExecStart=/usr/local/bin/wedge100s-mgmt-affinity.sh
    RemainAfterExit=yes

    [Install]
    WantedBy=multi-user.target
""")

SSH_AFFINITY_PATH = "/etc/systemd/system/ssh.service.d/cpu-affinity.conf"
SSH_AFFINITY = textwrap.dedent("""\
    [Service]
    CPUAffinity=2
""")

NETWORKING_AFFINITY_PATH = "/etc/systemd/system/networking.service.d/cpu-affinity.conf"
NETWORKING_AFFINITY = textwrap.dedent("""\
    [Service]
    CPUAffinity=2
""")


class CpuAffinityTask(ConfigTask):

    def check(self) -> list:
        changes = []

        out, _, _ = self.ssh.run(f"cat {AFFINITY_SCRIPT_PATH} 2>/dev/null", timeout=10)
        if "wedge100s-mgmt-affinity" not in out:
            changes.append(Change(
                item="mgmt-affinity boot script",
                current=out.strip() or "missing",
                desired=AFFINITY_SCRIPT_PATH,
                cmd="_write_script",
            ))

        out, _, _ = self.ssh.run(f"cat {AFFINITY_SERVICE_PATH} 2>/dev/null", timeout=10)
        if "wedge100s-mgmt-affinity" not in out:
            changes.append(Change(
                item="wedge100s-mgmt-affinity.service",
                current=out.strip() or "missing",
                desired=AFFINITY_SERVICE_PATH,
                cmd="_write_service",
            ))

        out, _, _ = self.ssh.run(f"cat {SSH_AFFINITY_PATH} 2>/dev/null", timeout=10)
        if "CPUAffinity" not in out:
            changes.append(Change(
                item="ssh.service CPUAffinity=2",
                current=out.strip() or "missing",
                desired=SSH_AFFINITY_PATH,
                cmd="_write_ssh_affinity",
            ))

        out, _, _ = self.ssh.run(f"cat {NETWORKING_AFFINITY_PATH} 2>/dev/null", timeout=10)
        if "CPUAffinity" not in out:
            changes.append(Change(
                item="networking.service CPUAffinity=2",
                current=out.strip() or "missing",
                desired=NETWORKING_AFFINITY_PATH,
                cmd="_write_networking_affinity",
            ))

        return changes

    def apply(self, changes: list) -> None:
        reload_needed = False

        for change in changes:
            if change.cmd == "_write_script":
                self._write_file(AFFINITY_SCRIPT_PATH, AFFINITY_SCRIPT)
                self.ssh.run(f"sudo chmod +x {AFFINITY_SCRIPT_PATH}", timeout=5)
                print("  [cpu_affinity] mgmt-affinity script installed", flush=True)

            elif change.cmd == "_write_service":
                self._write_file(AFFINITY_SERVICE_PATH, AFFINITY_SERVICE)
                reload_needed = True
                print("  [cpu_affinity] mgmt-affinity.service installed", flush=True)

            elif change.cmd == "_write_ssh_affinity":
                self.ssh.run(f"sudo mkdir -p $(dirname {SSH_AFFINITY_PATH})", timeout=5)
                self._write_file(SSH_AFFINITY_PATH, SSH_AFFINITY)
                reload_needed = True
                print("  [cpu_affinity] ssh.service CPUAffinity=2 drop-in installed", flush=True)

            elif change.cmd == "_write_networking_affinity":
                self.ssh.run(f"sudo mkdir -p $(dirname {NETWORKING_AFFINITY_PATH})", timeout=5)
                self._write_file(NETWORKING_AFFINITY_PATH, NETWORKING_AFFINITY)
                reload_needed = True
                print("  [cpu_affinity] networking.service CPUAffinity=2 drop-in installed", flush=True)

        if reload_needed:
            self.ssh.run("sudo systemctl daemon-reload", timeout=15)

        # Enable and run the affinity service now (don't wait for reboot)
        self.ssh.run(
            "sudo systemctl enable wedge100s-mgmt-affinity.service 2>/dev/null || true",
            timeout=10,
        )
        self.ssh.run(
            "sudo systemctl start wedge100s-mgmt-affinity.service 2>/dev/null || true",
            timeout=15,
        )

    def verify(self) -> bool:
        remaining = self.check()
        if remaining:
            for c in remaining:
                print(f"  [cpu_affinity] FAIL: {c}")
            return False
        # Confirm eth0 IRQ is actually on CPU 2
        out, _, _ = self.ssh.run(
            "grep -w eth0 /proc/interrupts | awk -F: '{print $1}' | tr -d ' ' | "
            "xargs -I{} cat /proc/irq/{}/smp_affinity 2>/dev/null | head -1",
            timeout=10,
        )
        if out.strip() and out.strip() != "4":
            print(f"  [cpu_affinity] WARN: eth0 IRQ affinity={out.strip()!r}, expected 4 (CPU 2)")
        return True

    def _write_file(self, path: str, content: str) -> None:
        import base64
        encoded = base64.b64encode(content.encode()).decode()
        self.ssh.run(
            f"sudo mkdir -p $(dirname {path}) && "
            f"echo {encoded} | base64 -d | sudo tee {path} > /dev/null",
            timeout=15,
        )
